
// Generated by `anchor build` and copied here verbatim — do not edit. See the
// note at the top of `deadweight-idl.ts` for why these live under `src/`.

export const DeadweightErrorCode = {
  IndexOutOfOrder: 6000,
  EmptyManifest: 6001,
  TooManyLines: 6002,
  EmptyItemId: 6003,
  ItemIdTooLong: 6004,
  ZeroQuantity: 6005,
  DeclaredNotPositive: 6006,
  VerdictDoesNotFollow: 6007,
  ArithmeticOverflow: 6008
};

export type DeadweightErrorName = keyof typeof DeadweightErrorCode;
